### ISSUE TITLE
Unable to delete uploaded file from profile

### ISSUE THREAD

**Issue by pandu-rao** [canonical-websites/www.canonical.com#102]

**Comment by nottrobin** [comment]
Hi @pandu-rao. Thanks for taking the time to file an issue.

As www.canonical.com has no profile page, I suspect it's for a different platform, and this bug should probably be filed elsewhere.

If you explain where you encountered this issue I'll gladly point you in the right direction.

**Comment by pandu-rao** [comment]
Now I understand. Here's the URL:
https://ldd.tbe.taleo.net/ldd03/ats/careers/candidateInfo.jsp?org=CANONICAL&cws=1

Its an external site, and it looks like Canonical is a customer of the service. You should bring it to their attention.

Please send me a link to the ticket you open on that system and I can close this.

Thanks.

**Comment by deadlight** [comment]
Thanks for the bug report; I'll investigate the issue and ascertain if the issue is something we can fix ourselves or if we need to file a bug with Taleo.

**Comment by pmahnke** [comment]
@deadlight any updates?

**Comment by deadlight** [comment]
When applying for a role you have the option of uploading a CV/resume and supporting files.

To remove these files, you can go to "View status" from the job listing page (when you are logged in to your account).

From here, go to "update my information" and then, near the bottom of the form there is a "Remove File..." for each file uploaded. Selecting this and saving the form will remove any uploads.

 - Karl
