### ISSUE TITLE
Please help to remove the first pictures in partners page

### ISSUE THREAD

**Issue by binli** [canonical-websites/www.canonical.com#123]
https://www.canonical.com/partners

The trademark of ubuntu in Chinese was registered by other company already.

**Comment by binli** [comment]
https://github.com/canonical-websites/www.canonical.com/pull/124

I made a pull request, :)

**Comment by nottrobin** [comment]
Who has this change been agreed with?

@pmahnke do you have thoughts?

**Comment by anthonydillon** [comment]
I believe this is correct. But we would like to leave the image row to separate the content. The is a suggestion to crop out the top part of the image.
