### ISSUE TITLE
discourse.ubuntu.com is still linked on the shop

### ISSUE THREAD

**Issue by setharnold** [canonical-websites/www.canonical.com#133]
## Summary

The discourse.ubuntu.com service was discontinued ages ago; but there is still a link to it from https://shop.canonical.com/

## Process

Visit https://shop.canonical.com/ . click on 'discourse' in the very top bar: it will go to http://discourse.ubuntu.com/ which will return a browser-specific error page that reports the server cannot be located.

Thanks

**Comment by pmahnke** [comment]
Thanks for filing this.

We have contacted the 3rd party who runs the shop to update the nav.

**Comment by deadlight** [comment]
The referenced link has been removed.
