### ISSUE TITLE
Partner page throws a 500

### ISSUE THREAD

**Issue by surajkika** [canonical-websites/www.canonical.com#137]
## Summary

Hey friends, the /partners page throws a 500 error https://www.canonical.com/partners

## Process

Click on the Partners page from https://www.canonical.com in main nav

## Current and expected result

Threw a 500 error, but was expecting to see how Canonical partners :)

## Screenshot
![screen shot 2017-07-11 at 13 45 37](https://user-images.githubusercontent.com/11191487/28068895-43b5ddd6-663f-11e7-80a2-b124703ca376.png)

**Comment by deadlight** [comment]
Thanks for reporting this.

We have fixed the feed issue that was causing these 500 errors and have improved the code to deal with such outages more gracefully.

Thanks,
Karl
