### ISSUE TITLE
Update about page content

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/www.canonical.com#142]

**Comment by frankiegranato** [comment]
Brief: https://docs.google.com/document/d/1ZrWt5GAnvsql0NKrj4c6UoRzJBBd6OzzcK5rxar2qts/edit

**Comment by joanasa89** [comment]
@deadlight Here the assets:
Dropboxfolder: https://www.dropbox.com/sh/zqg9pco6z4v1w4d/AAAVrFAUsQ-_672pCx10p0dea?dl=0
and the photos:
https://assets.ubuntu.com/v1/74c207a8-Anand+Krishnan-canonical.png
https://assets.ubuntu.com/v1/43ce56dc-Mark-canonical.png
https://assets.ubuntu.com/v1/7cebe87e-Jane-canonical.png
https://assets.ubuntu.com/v1/5e690c57-Mike-canonical.png
https://assets.ubuntu.com/v1/6d7138e6-sedbutter-canonical.png
