### ISSUE TITLE
Update Bejing office address on - www.canonical.com/about - for 11 August 2017

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.canonical.com#162]
On 25 July 2017 at 16:44, Nancy Huang <nancy.huang@canonical.com> wrote:

As Canonical Beijing office is moving over to a new location from 11 August 2017, please could you help to make necessary update to reflect the address and contact number changes through Canonical websites and other media related to marketing? the new address is as below for your information (in both English and Chinese):

Address: Unit 1118-19, Level 11, China World Office 1, 1 Jianguomenwai Avenue, Chaoyang District, Beijing 100004
                北京市朝阳区建国门外大街1号国贸写字楼1座11层1118-19室
Contract number: 010 5737 9099

Please kindly let us know if it's fine for you. 

Many Thanks
Nancy

**Comment by deadlight** [comment]
Updated cn.ubuntu.com on the live CMS
