### ISSUE TITLE
Bad formatting on Partners page

### ISSUE THREAD

**Issue by benjamincampbell** [canonical-websites/www.canonical.com#163]
## Summary

After a certain browser width, the Partners page has some poorly formatted text in the 'Ubuntu on PC' area. The words overlap the picture, creating a difficult contrast in colors to read the text.
## Process

For me, when the window was sized to a width of around 973 or greater pixels, the issue occurred. On shorter widths the formatting was fine, with the picture beside the text, but not overlapping. I am using Google Chrome version 59, Windows 10, and a 1680x1050 monitor. 

## Current and expected result

I had my Chrome windows full screen, and navigated to the Partners page. I scrolled down and noticed the difficult to read text. I tried resizing the window to a shorter width, which worked much better.

## Screenshot
![ubuntu_on_pc_error](https://user-images.githubusercontent.com/3676620/28977462-1cff1c1e-7910-11e7-8a90-065d27ba2c93.png)

**Comment by deadlight** [comment]
Thanks for the bug report. We will fix this as part of the CSS upgrade to this page.

**Comment by deadlight** [comment]
@benjamincampbell this has been fixed on the latest master version of the site and will be released to the live site very soon.

Thanks again for the report.

**Comment by barrymcgee** [comment]
Addressed in https://github.com/canonical-websites/www.canonical.com/pull/181 - this fix will be live this week. Thank you.
