### ISSUE TITLE
missing footer on /service, /projects, /projects/directory and /about pages

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.canonical.com#200]
## Summary

The footer is missing on /service, /projects, /projects/directory and /about pages

## Current and expected result

All pages should have the footer

## Screenshot

![image](https://user-images.githubusercontent.com/441217/30051417-d86e9e08-9219-11e7-9606-11376f88dde7.png)

**Comment by deadlight** [comment]
@Caleb-Ellis This will be another good task for you to take a look at. It'll cover how the templates are put together on the site with nested includes.
