### ISSUE TITLE
Update the Japan office address on this page

### ISSUE THREAD

**Issue by campbieil** [canonical-websites/www.canonical.com#206]
## Summary

The address of the Japan office is incorrect on this page in the google map

## Process

Visit the page

## Current and expected result

The correct address for the office is:
Address: 3rd Floor, Sanno Park Tower,2-11-1 Nagata-cho,Chiyoda-ku,Tokyo 100-6162 Japan​
Phone: +81 3-6205-3075
Email: info-jp@canonical.com

## Screenshot

[if relevant, include a screenshot]

**Comment by frankiegranato** [comment]
This bug concerns https://www.canonical.com/about - the Tokyo, Japan label.

**Comment by anthonydillon** [comment]
This has gone live.
