### ISSUE TITLE
Update the executives in the about page

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.canonical.com#233]
Rebecca will check who should be on the exec on the page. Then the execs should be updated on the about us page.

**Comment by frankiegranato** [comment]
This is blocked until we hear from Rebecca.

**Comment by frankiegranato** [comment]
This is unblocked. 
Our instruction from Sarah and Rebecca is to simply Remove Anand Krishnan from the list. 
No further actions are required at this time.
