### ISSUE TITLE
Please update copyright notice

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.canonical.com#235]
Allegra from our legal department has informed us that: Copyright notices should be included at the foot of all pages of our websites and should be kept the same across the site. Copyright notice will need to include the year of first publication (for websites this means the year it was last updated). 

Therefore, I suggest we update the copyright notice at the foot of the site to read: © 2018 Canonical Ltd. Ubuntu and Canonical are registered trademarks of Canonical Ltd.

(as soon as we update the copyright, the site has been updated right?)

**Comment by CalvinHartwell** [comment]
@frankiegranato is this still a problem?

**Comment by anthonydillon** [comment]
@CalvinHartwell yes this is still an outstanding task.
