### ISSUE TITLE
Responsive web design issue (large screens)

### ISSUE THREAD

**Issue by CalvinHartwell** [canonical-websites/www.canonical.com#236]
## Summary

The website appears to use a responsive design which works fine on most screens, but has issues on large screens (4k and higher) with high resolution. Please see the image:
[https://i.imgur.com/uEH5jbs.png](https://i.imgur.com/uEH5jbs.png)

## Process

Open the website on a large format screen in 4k or higher resolution. 

## Current and expected result

Website content should make better use of the space on the screen. 

## Screenshot

[https://i.imgur.com/uEH5jbs.png](https://i.imgur.com/uEH5jbs.png)

**Comment by anthonydillon** [comment]
Thank you for prompting is to improve our designs on extra large screen. We will hopefully get some design time on this and have a solution soon.

**Comment by CalvinHartwell** [comment]
@anthonydillon thnx
