### ISSUE TITLE
Canonical Career Vacancy List offline

### ISSUE THREAD

**Issue by MCPerina** [canonical-websites/www.canonical.com#240]
## Summary

Career vacancy list offline, various methods to reach fail.

## Process

All linked methods, from canonical site to vacancies list, including direct link "https://www.canonical.com/careers/all-vacancies" fail to produce list results.  Feed appears offline and produces GitHub Issue link.

## Current and expected result

Current result provides link to GitHub Issue submission.

Expected result was previously list of 36 open positions

## Screenshot

[if relevant, include a screenshot]

**Comment by anthonydillon** [comment]
Thank you for reporting this issue. The careers feed is back up and running.
