### ISSUE TITLE
Career page shows "Error:Feed failed to load."

### ISSUE THREAD

**Issue by ltmvic51** [canonical-websites/www.canonical.com#242]
## Summary

Career page shows "Error:Feed failed to load."

## Process

Click on Career page label, and go to "see all vacancies", this message shows when the page finished loading.

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by anthonydillon** [comment]
Thank you for reporting this issue. The careers page is now back up and running.
