### ISSUE TITLE
Add "Contact us" link in footer of canonical.com 

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.canonical.com#245]
Please add a "Contact us" link in footer of canonical.com. Please follow the styling and position of the same button on ubuntu.com (see screen shot). 
![image](https://user-images.githubusercontent.com/17002826/37394337-67784f40-276b-11e8-8258-26e717194aad.png)

**Comment by steverydz** [comment]
Pull request: https://github.com/canonical-websites/www.canonical.com/pull/246
