### ISSUE TITLE
Canonical Careers website is not working properly

### ISSUE THREAD

**Issue by CalvinHartwell** [canonical-websites/www.canonical.com#255]
## Summary

The Canonical Careers website section is not functioning: [https://www.canonical.com/careers/all-vacancies](https://www.canonical.com/careers/all-vacancies). 

## Process

Visit the link: [https://www.canonical.com/careers/all-vacancies](https://www.canonical.com/careers/all-vacancies)

## Current and expected result

Website should work, but does not. 

## Screenshot

[https://i.imgur.com/vAN16uN.png](https://i.imgur.com/vAN16uN.png)

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to file this issue.
This has been fixed via #259 this should be live shortly.
