### ISSUE TITLE
Error on All current vacancies page.

### ISSUE THREAD

**Issue by borracciaBlu** [canonical-websites/www.canonical.com#256]
## Summary
Error on All current vacancies page.

## Process
https://www.canonical.com/careers/all-vacancies

## Current and expected result
List of vacancies :)

## Screenshot
![screenshot 5](https://user-images.githubusercontent.com/2061731/38029076-95de2cf8-32e0-11e8-995c-5e652e9acfeb.png)

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to file this issue.
This has been fixed via #259 this should be live shortly.
