### ISSUE TITLE
Vacancies feed doesn't load up on Canonical Careers sections

### ISSUE THREAD

**Issue by sradhakrishna** [canonical-websites/www.canonical.com#257]
## Summary

The vacancies feed doesn't load up on Canonical Careers section here: https://www.canonical.com/careers/all-vacancies. 

## Process

Open https://www.canonical.com/careers and click on See all Vacancies link. A page showing "Error:Feed failed to load. If you have time, please file an issue" shows up

## Current and expected result

Expected result: See the list of vacancies in Canonical

## Screenshot

![image](https://user-images.githubusercontent.com/375461/38034722-82bf7aca-32c0-11e8-812a-48bbb2b11208.png)

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to file this issue.
This has been fixed via #259 this should be live shortly.
