### ISSUE TITLE
Canonical-Careers: 'all vacancies' feed does not load

### ISSUE THREAD

**Issue by ulmer-a** [canonical-websites/www.canonical.com#258]
## Summary

opening the page for vacancy at canonical on Safari takes way too long and results in an error 'feed failed to load'

## Process

the 'careers'-link on the ubuntu.com main page redirected me to 'https://www.canonical.com/careers', which worked fine. As soon as I clicked on the link 'See all vacancies', it took maybe 30 seconds and resulted in an error 'feed failed to load'.

https://www.canonical.com/careers/all-vacancies

I tried again about half an hour later and it still did not work.

## Screenshot

<img width="1188" alt="screenshot-canonical-vacancies" src="https://user-images.githubusercontent.com/35337783/38048875-fb2a7fd6-32c6-11e8-9ab0-a6075b3aec01.png">

EDIT: after posting this issue, I noticed a few more people have the same problem, so this is probably a duplicate... Should I delete the issue?

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to file this issue.
This has been fixed via #259 this should be live shortly.
