### ISSUE TITLE
OpenStack User Survey quote is five years old

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.canonical.com#294]
[The products page](https://www.canonical.com/products) has a quote in large print:

> # “Ubuntu remains the most popular operating system for OpenStack deployments„
> ## OpenStack User Survey, November 2013

That was half a decade ago. Whatever reminder was set up, to update the quote each year, hasn’t been working.

([According to the latest survey](https://www.openstack.org/analytics), the most popular OS for OpenStack is still Ubuntu — 38% to CentOS’s 31%.)

**Comment by pmahnke** [comment]
@matthewpaulthomas you should have reminded us 3 years ago!

**Comment by pmahnke** [comment]
shame

**Comment by matthewpaulthomas** [comment]
I’m sorry, I didn’t know the page existed until last week…

That was a roundabout way of suggesting that maybe it would be a good idea to set up a generalized system to report an issue for updating X page whenever Y event happens. For example, remind us to:
- update this products page, whenever the “See prior survey reports” section on https://www.openstack.org/user-survey changes
- update the copyright date in any site’s footer, on the first change we make to the site after January 1st
- update the list of Livepatchable releases, whenever an LTS is released or reaches EOL ([www.ubuntu.com#3447](https://github.com/canonical-websites/www.ubuntu.com/issues/3447#issuecomment-402284841)).

**Comment by anasereijo** [comment]
The website is being redesigned with new content. Closing this issue.
