### ISSUE TITLE
voices.canonical.com is still a thing

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.canonical.com#299]
[voices.canonical.com](http://voices.canonical.com/) still exists, and still shows posts from as recently as two days ago. However:
- The header navigation is years out of date with the rest of [canonical.com](https://canonical.com/).
- Searching for anything [returns a 404 error](https://www.canonical.com/search/node).
- The “Latest official posts” are from 2014 and 2015.
- In the “Featured Blogs”, [one returns a 500 error](http://voices.canonical.com/ubuntuone/), while [another returns a 404 error](http://developer.ubuntu.com/community/app-developer-blog/).
- Deep links into the site return a 500 error, probably for the same reason, for example the “[this post](http://voices.canonical.com/ubuntuone/2014/06/03/moving-your-content-away-from-ubuntu-one-file-services/)” link at the end of [“Shutting down Ubuntu One file services”](https://blog.ubuntu.com/2014/04/02/shutting-down-ubuntu-one-file-services).
- Several of the “People” are duplicated, and several no longer work for Canonical.
- The footer says “© 2010 Canonical Ltd.”

Probably the posts that are hosted on voices.canonical.com should be migrated to blog.ubuntu.com with specific redirects, then all other URLs should be redirected to blog.ubuntu.com/.

(When migrating posts, be sure to migrate any images too, to avoid a repeat of [blog.ubuntu.com#377](https://github.com/canonical-websites/blog.ubuntu.com/issues/377).)

**Comment by pmahnke** [comment]
closing - the coordinated shutdown of voices has been requested in this [RT](https://portal.admin.canonical.com/C107348)
