### ISSUE TITLE
Error message on Vacancies page

### ISSUE THREAD

**Issue by maxsond** [canonical-websites/www.canonical.com#306]
## Summary

Error message on Vacancies page

## Process

Open https://www.canonical.com/careers/all-vacancies in latest Chrome or Firefox (I'm on Windows 8.1 if it matters)

## Current and expected result

Expected: I see a (possibly empty) list of vacancies at Canonical.
Current: Where I would expect to see the vacancies, I instead see this message: Error:Feed failed to load. If you have time, please file an issue. 

## Screenshot

![canonical](https://user-images.githubusercontent.com/1946457/46638420-58a79500-cb50-11e8-9428-01f1a5cc6b25.png)

**Comment by anthonydillon** [comment]
Thank you for taking the time to file this issue. We will try and get it fixed as soon as possible.

**Comment by pmahnke** [comment]
This has now been resolved... thank you!
