### ISSUE TITLE
https://www.canonical.com/careers/all-vacancies fails to load feed

### ISSUE THREAD

**Issue by FilterSelect** [canonical-websites/www.canonical.com#309]
## Summary

The current vacancies page on canonical.com fails to load the feed.

## Process

Fully updated Kubuntu 18.04 & Firefox

## Current and expected result

I expected to see a list of jobs, I got what you see in the screenshot ;)

## Screenshot

As so: 
![screenshot_20181009_231436](https://user-images.githubusercontent.com/4920763/46668869-7ab91a00-cc19-11e8-81df-d7d5835cf83d.png)

![image](https://user-images.githubusercontent.com/4920763/46668926-9a504280-cc19-11e8-8512-e0bb7344b70a.png)

**Comment by pmahnke** [comment]
This has now been resolved... thank you!
