### ISSUE TITLE
Careers page failed to load fully with message: Feed failed to load

### ISSUE THREAD

**Issue by DiogoConstantino** [canonical-websites/www.canonical.com#310]
## Summary

Careers page failed to load fully with message: Feed failed to load

## Process

Just navigate to the Careers page

## Current and expected result

Content should be loaded, including a list of currently open positions at Canonical

## Screenshot

![captura de ecra de 2018-10-09 15-22-25](https://user-images.githubusercontent.com/9408012/46672237-2d1bbd80-cbd7-11e8-8731-67ac6423f48f.png)

**Comment by pmahnke** [comment]
This has now been resolved... thank you!
