### ISSUE TITLE
Staging deploy seems broken?

### ISSUE THREAD

**Issue by barrymcgee** [canonical-websites/www.canonical.com#318]
## Summary

I successfully pushed a deployment to Staging yesterday but can't see the change on Staging.

<img width="671" alt="screenshot 2018-12-13 at 12 47 09" src="https://user-images.githubusercontent.com/505570/49939623-442ba400-fed5-11e8-9ec6-a5597d7f9348.png">

If this successfully deployed, the spelling mistakes 'DEPRICIATED' should no longer be present here:

https://www.staging.canonical.com/projects/directory

![db9e104ab0bf77dea2af08e31e3e9aa1 _screenshot 202018-12-12 20at 2010 01 28](https://user-images.githubusercontent.com/505570/49939764-9e2c6980-fed5-11e8-9dd1-39b076665cd8.png)

**Comment by nottrobin** [comment]
I don't think you followed the [deployment steps](https://wiki.canonical.com/ProductStrategyTeam/WebDevelopment/Canonical#Building_.26_releasing) properly. The first step is to run the "www.canonical.com-code-build" job and then click the link at the bottom of the output to run "www.canonical.com-deploy-to-staging" job with the correct build label. But the last time that job was run is 17-Sep-2018 15:05.

I've kicked it off again just now, hopefully it will go smoothly. I'll close this for now, as I currently don't have a reason to think there's anything wrong with the release process. But we can open up another one if we run into troubles.
