### ISSUE TITLE
/careers - UX - sketches

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/www.canonical.com#320]
Sketch the perfect, ideal example of a careers webpage for canonical.com

**Comment by pmahnke** [comment]
@Greggless can I see this? can you link to it here?

**Comment by Greggless** [comment]
# Careers overview
![careers overview](https://user-images.githubusercontent.com/23459065/51686285-064b9080-1fe8-11e9-82a6-6f9e742ddd53.png)

# Team page - detailed
![team page - detailed](https://user-images.githubusercontent.com/23459065/51686320-13687f80-1fe8-11e9-8841-308efbfce3a5.png)

# Team page - minimal
![team page - minimal](https://user-images.githubusercontent.com/23459065/51686328-17949d00-1fe8-11e9-930c-2256233ebe5e.png)
