### ISSUE TITLE
Image unnecessarily large on /products

### ISSUE THREAD

**Issue by mthaddon** [canonical-websites/www.canonical.com#322]
https://www.canonical.com/products shows https://assets.ubuntu.com/v1/c6504e94-Dell_XPS_Laptop_Front-Desktop.png as follows: 

<img src="https://assets.ubuntu.com/v1/c6504e94-Dell_XPS_Laptop_Front-Desktop.png" width="800" height="403" alt="">

The image itself is 2721 by 1372 and 1.1MB in size.

**Comment by mthaddon** [comment]
I meant to include the HTML, which has:

img src="https://assets.ubuntu.com/v1/c6504e94-Dell_XPS_Laptop_Front-Desktop.png" width="800" height="403" alt=""

So the image itself is displayed at 800 x 403 pixels.

**Comment by nottrobin** [comment]
Thanks @mthaddon, well spotted. I've filed https://github.com/canonical-websites/www.canonical.com/pull/323 to fix it.
