### ISSUE TITLE
Homepage - design

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/www.canonical.com#341]

**Comment by anasereijo** [comment]
@spencerbygraves can you please estimate this issue? thank you

**Comment by spencerbygraves** [comment]
Design for the homepage based on the wireframe done in Malta. Reviewed with @clagom and needs final content.

### Malta wireframe

![image](https://user-images.githubusercontent.com/9105999/54287448-93997300-459d-11e9-9df5-14694337d01f.png)

### Homepage design

![image](https://user-images.githubusercontent.com/9105999/54287296-4b7a5080-459d-11e9-94a3-7e450e58dce9.png)

**Comment by spencerbygraves** [comment]
Will handover to @deadlight

**Comment by spencerbygraves** [comment]
@deadlight @clagom the navigation for canonical.com is still in progress so we will need to sync with @waynecrosby and @carlaberkers when we come to build it.
