### ISSUE TITLE
Finalise design systems - design

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/www.canonical.com#343]

**Comment by anasereijo** [comment]
@spencerbygraves can you please estimate this issue? thank you

**Comment by spencerbygraves** [comment]
Design for the guidelines part of canonical.com/design.

![image](https://user-images.githubusercontent.com/9105999/54287629-ed9a3880-459d-11e9-9521-47e210590416.png)

**Comment by spencerbygraves** [comment]
Will handover to @deadlight
