### ISSUE TITLE
Update the SASS parser to provide a relevant include-path

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.canonical.com#99]
Soon canonical-vanilla-theme [will expect to find vanilla-framework within the SASS include paths](https://github.com/ubuntudesign/canonical-vanilla-theme/issues/31). So we will have to update the SASS parser to include `node_modules` in the include-path.

We will also need to start using NPM 3 or newer, so that vanilla-framework is pulled directly into `node_modules` rather than some sub-folder.

**Comment by pmahnke** [comment]
@nottrobin any updates?

**Comment by anthonydillon** [comment]
This will happen as part of upgrading to vanilla-brochure-theme.

**Comment by deadlight** [comment]
@anthonydillon was this done?

**Comment by anthonydillon** [comment]
Yes this has been done: https://github.com/canonical-websites/www.canonical.com/blob/7a53f1affba455cb7bc85044f9340d7e7ead0142/package.json#L7

**Comment by nottrobin** [comment]
Oooh! Is that line display widget new?

**Comment by anthonydillon** [comment]
Must be, I just linked to the line of code.
